from pathlib import Path
p=Path('app/src/main/java/com/mh/analysis/MainActivityV24.kt')
s=p.read_text()
old='''thread{try{val(out,credits)=FcsClient.seedForPeriod(key,reqSymbol,reqPeriod,true);runOnUiThread{busy=false;if(credits>0)addUsage(credits);calls.text="Analysis history calls: ${usage()}/500";if(reqSymbol!=symbol||reqPeriod!=period){status.text="MARKET CHANGED • press NEW ANALYZE for $symbol $period";return@runOnUiThread};candles=out;loadedSymbol=reqSymbol;loadedPeriod=reqPeriod;performAnalysis()}}catch(e:Exception){runOnUiThread{busy=false;val fallback=FcsClient.peek(reqSymbol,reqPeriod,220).orEmpty();if(reqSymbol==symbol&&reqPeriod==period&&fallback.size>=60){candles=fallback;loadedSymbol=reqSymbol;loadedPeriod=reqPeriod;status.text="PROVIDER REFRESH UNAVAILABLE • analyzing latest saved market depth";performAnalysis()}else status.text="ANALYSIS DATA ERROR\\n${e.message}\\nLive FCS WebSocket chart remains active."}}}'''
new='''thread{try{val(out,credits)=FcsClient.seedForPeriod(key,reqSymbol,reqPeriod,true);runOnUiThread{busy=false;if(credits>0)addUsage(credits);calls.text="Analysis history calls: ${usage()}/500";if(reqSymbol!=symbol||reqPeriod!=period){status.text="MARKET CHANGED • press NEW ANALYZE for $symbol $period";return@runOnUiThread};candles=out;loadedSymbol=reqSymbol;loadedPeriod=reqPeriod;renderHistory(out);performAnalysis()}}catch(e:Exception){runOnUiThread{busy=false;val fallback=FcsClient.peek(reqSymbol,reqPeriod,220).orEmpty();if(reqSymbol==symbol&&reqPeriod==period&&fallback.size>=60){candles=fallback;loadedSymbol=reqSymbol;loadedPeriod=reqPeriod;renderHistory(fallback);status.text="PROVIDER REFRESH UNAVAILABLE • analyzing latest saved market depth";performAnalysis()}else status.text="ANALYSIS DATA ERROR\\n${e.message}\\nLive WebSocket chart remains active."}}}'''
if old not in s: raise SystemExit('Missing v26 analyze patch target')
s=s.replace(old,new,1)
s=s.replace('MS • v25 • SINGLE LIVE SOCKET ENGINE','MS • v26 • DIRECT WEBSOCKET LIVE CHART')
p.write_text(s)
