from pathlib import Path

engine=Path('app/src/main/java/com/mh/analysis/AnalysisEngine.kt')
s=engine.read_text()

anchor1='''        val bullLevelLadder=bullLadderBase!=null&&bullOppPool!=null&&last.c>bullLadderBase&&abs(last.l-bullLadderBase)<=a*.30&&(bullOppPool.price-last.c)>=a*.55&&(pressureBull||momentumBull||displacementBull||bosBull)\n        val bearLevelLadder=bearLadderBase!=null&&bearOppPool!=null&&last.c<bearLadderBase&&abs(last.h-bearLadderBase)<=a*.30&&(last.c-bearOppPool.price)>=a*.55&&(pressureBear||momentumBear||displacementBear||bosBear)\n'''
insert1=anchor1+'''\n        // Additional structure confirmations: impulse pause levels, participant body-break,\n        // untouched-liquidity magnet behavior and large-wick fill continuation.\n        val bullBodyBreakLevel=oppositeBodyBreakLevel(c,"BUY",a)\n        val bearBodyBreakLevel=oppositeBodyBreakLevel(c,"SELL",a)\n        val bullPauseLevel=impulsePauseLevel(c,"BUY",a)\n        val bearPauseLevel=impulsePauseLevel(c,"SELL",a)\n        val bullPauseReaction=bullPauseLevel?.let{lv->abs(last.c-lv)<=a*.60&&last.l<=lv+a*.18&&last.c>=lv-a*.04&&last.c>last.o&&(pressureBull||bullReaction||bullBodyBreakLevel!=null||rsiBullDiv)}==true\n        val bearPauseReaction=bearPauseLevel?.let{lv->abs(last.c-lv)<=a*.60&&last.h>=lv-a*.18&&last.c<=lv+a*.04&&last.c<last.o&&(pressureBear||bearReaction||bearBodyBreakLevel!=null||rsiBearDiv)}==true\n        val bullParticipantShift=bullBodyBreakLevel!=null&&(liqSweepBull||stopHuntBull||fakeBull||chochBull||nearSupport||bullReaction||srFlipBull)\n        val bearParticipantShift=bearBodyBreakLevel!=null&&(liqSweepBear||stopHuntBear||fakeBear||chochBear||nearResistance||bearReaction||srFlipBear)\n        val bullFrontRun=bullOppPool?.let{untouchedLiquidityFrontRun(c,"BUY",it.price,a)}==true&&(momentumBull||pressureBull||trendBull||bosBull)\n        val bearFrontRun=bearOppPool?.let{untouchedLiquidityFrontRun(c,"SELL",it.price,a)}==true&&(momentumBear||pressureBear||trendBear||bosBear)\n        val bullWickFillSource=bearWickSource\n        val bearWickFillSource=bullWickSource\n        val bullWickFill=bullWickFillSource?.let{x->val base=max(x.o,x.c);x.h-base>=a*.35&&last.c>base+a*.05&&last.c<x.h+a*.08&&last.c>last.o&&(pressureBull||momentumBull||bosBull||displacementBull)}==true\n        val bearWickFill=bearWickFillSource?.let{x->val base=min(x.o,x.c);base-x.l>=a*.35&&last.c<base-a*.05&&last.c>x.l-a*.08&&last.c<last.o&&(pressureBear||momentumBear||bosBear||displacementBear)}==true\n'''
if anchor1 not in s: raise SystemExit('v33 anchor1 not found')
s=s.replace(anchor1,insert1,1)

anchor2='''        if(bullWickReclaim)b(16,"Dominant lower-wick reclaim / wick-fill rejection")\n        if(bearWickReclaim)s(16,"Dominant upper-wick reclaim / wick-fill rejection")\n'''
insert2=anchor2+'''        if(bullPauseReaction)b(18,"Impulse-pause support level revisited and defended")\n        if(bearPauseReaction)s(18,"Impulse-pause resistance level revisited and rejected")\n        if(bullParticipantShift)b(15,"Seller body broken after liquidity reaction — buyer control confirmed")\n        if(bearParticipantShift)s(15,"Buyer body broken after liquidity reaction — seller control confirmed")\n        if(bullFrontRun)b(9,"Untouched buy-side liquidity remains a continuation magnet")\n        if(bearFrontRun)s(9,"Untouched sell-side liquidity remains a continuation magnet")\n        if(bullWickFill)b(16,"Upper-wick body break opened a wick-fill continuation target")\n        if(bearWickFill)s(16,"Lower-wick body break opened a wick-fill continuation target")\n'''
if anchor2 not in s: raise SystemExit('v33 anchor2 not found')
s=s.replace(anchor2,insert2,1)

anchor3='''        val bullTrendlineFamily=bullTrendlineReaction&&(trendBull||momentumBull||rsiBullDiv||chochBull||bosBull)\n        val bearTrendlineFamily=bearTrendlineReaction&&(trendBear||momentumBear||rsiBearDiv||chochBear||bosBear)\n        val bullWickFamily=bullWickReclaim&&(liqSweepBull||stopHuntBull||nearSupport||bullReaction||chochBull)\n        val bearWickFamily=bearWickReclaim&&(liqSweepBear||stopHuntBear||nearResistance||bearReaction||chochBear)\n        val bullFamily=listOf(bullLiquidity,bullRetest,bullContinuation,bullChoch,bullBreakout,bullLevelReaction,bullTrendlineFamily,bullLiquidityRoute,bullLevelLadder,bullWickFamily).count{it};val bearFamily=listOf(bearLiquidity,bearRetest,bearContinuation,bearChoch,bearBreakout,bearLevelReaction,bearTrendlineFamily,bearLiquidityRoute,bearLevelLadder,bearWickFamily).count{it}\n'''
insert3='''        val bullTrendlineFamily=bullTrendlineReaction&&(trendBull||momentumBull||rsiBullDiv||chochBull||bosBull)\n        val bearTrendlineFamily=bearTrendlineReaction&&(trendBear||momentumBear||rsiBearDiv||chochBear||bosBear)\n        val bullWickFamily=bullWickReclaim&&(liqSweepBull||stopHuntBull||nearSupport||bullReaction||chochBull)\n        val bearWickFamily=bearWickReclaim&&(liqSweepBear||stopHuntBear||nearResistance||bearReaction||chochBear)\n        val bullPauseFamily=bullPauseReaction&&(bullParticipantShift||momentumBull||chochBull||bosBull)\n        val bearPauseFamily=bearPauseReaction&&(bearParticipantShift||momentumBear||chochBear||bosBear)\n        val bullParticipantFamily=bullParticipantShift&&(pressureBull||momentumBull||chochBull||bosBull)\n        val bearParticipantFamily=bearParticipantShift&&(pressureBear||momentumBear||chochBear||bosBear)\n        val bullWickFillFamily=bullWickFill&&(momentumBull||pressureBull||bosBull||displacementBull)\n        val bearWickFillFamily=bearWickFill&&(momentumBear||pressureBear||bosBear||displacementBear)\n        val bullFamily=listOf(bullLiquidity,bullRetest,bullContinuation,bullChoch,bullBreakout,bullLevelReaction,bullTrendlineFamily,bullLiquidityRoute,bullLevelLadder,bullWickFamily,bullPauseFamily,bullParticipantFamily,bullWickFillFamily).count{it};val bearFamily=listOf(bearLiquidity,bearRetest,bearContinuation,bearChoch,bearBreakout,bearLevelReaction,bearTrendlineFamily,bearLiquidityRoute,bearLevelLadder,bearWickFamily,bearPauseFamily,bearParticipantFamily,bearWickFillFamily).count{it}\n'''
if anchor3 not in s: raise SystemExit('v33 anchor3 not found')
s=s.replace(anchor3,insert3,1)

anchor4='''        if(dir=="BUY"&&bullLevelLadder&&bullLadderBase!=null)candidates+="level-ladder retest" to bullLadderBase\n        if(dir=="SELL"&&bearLevelLadder&&bearLadderBase!=null)candidates+="level-ladder retest" to bearLadderBase\n'''
insert4=anchor4+'''        if(dir=="BUY"&&bullPauseFamily&&bullPauseLevel!=null)candidates+="impulse-pause support retest" to bullPauseLevel\n        if(dir=="SELL"&&bearPauseFamily&&bearPauseLevel!=null)candidates+="impulse-pause resistance retest" to bearPauseLevel\n        if(dir=="BUY"&&bullParticipantFamily&&bullBodyBreakLevel!=null)candidates+="seller-body break retest" to bullBodyBreakLevel\n        if(dir=="SELL"&&bearParticipantFamily&&bearBodyBreakLevel!=null)candidates+="buyer-body break retest" to bearBodyBreakLevel\n        if(dir=="BUY"&&bullWickFillFamily&&bullWickFillSource!=null)candidates+="upper-wick base retest" to max(bullWickFillSource.o,bullWickFillSource.c)\n        if(dir=="SELL"&&bearWickFillFamily&&bearWickFillSource!=null)candidates+="lower-wick base retest" to min(bearWickFillSource.o,bearWickFillSource.c)\n'''
if anchor4 not in s: raise SystemExit('v33 anchor4 not found')
s=s.replace(anchor4,insert4,1)

anchor5='''        val familyName=when{dir=="BUY"&&bullLiquidityRoute->"liquidity-to-liquidity rotation";dir=="SELL"&&bearLiquidityRoute->"liquidity-to-liquidity rotation";dir=="BUY"&&bullWickFamily->"dominant-wick reclaim reversal";dir=="SELL"&&bearWickFamily->"dominant-wick reclaim reversal";dir=="BUY"&&bullTrendlineFamily->"trendline third-touch rejection";dir=="SELL"&&bearTrendlineFamily->"trendline third-touch rejection";dir=="BUY"&&bullLevelLadder->"level-ladder continuation";dir=="SELL"&&bearLevelLadder->"level-ladder continuation";dir=="BUY"&&bullLiquidity->"clustered liquidity / SL-hunt reversal";dir=="SELL"&&bearLiquidity->"clustered liquidity / SL-hunt reversal";dir=="BUY"&&bullRetest->"breakout + support-flip retest";dir=="SELL"&&bearRetest->"breakdown + resistance-flip retest";dir=="BUY"&&bullChoch->"CHoCH reversal";dir=="SELL"&&bearChoch->"CHoCH reversal";dir=="BUY"&&bullLevelReaction->"multi-touch level reaction";dir=="SELL"&&bearLevelReaction->"multi-touch level reaction";dir=="BUY"&&bullBreakout->"breakout momentum continuation";dir=="SELL"&&bearBreakout->"breakout momentum continuation";else->"established trend pullback"}\n'''
insert5='''        val familyName=when{dir=="BUY"&&bullPauseFamily->"impulse-pause level reaction";dir=="SELL"&&bearPauseFamily->"impulse-pause level reaction";dir=="BUY"&&bullParticipantFamily->"participant body-break reversal";dir=="SELL"&&bearParticipantFamily->"participant body-break reversal";dir=="BUY"&&bullWickFillFamily->"large-wick fill continuation";dir=="SELL"&&bearWickFillFamily->"large-wick fill continuation";dir=="BUY"&&bullLiquidityRoute->"liquidity-to-liquidity rotation";dir=="SELL"&&bearLiquidityRoute->"liquidity-to-liquidity rotation";dir=="BUY"&&bullWickFamily->"dominant-wick reclaim reversal";dir=="SELL"&&bearWickFamily->"dominant-wick reclaim reversal";dir=="BUY"&&bullTrendlineFamily->"trendline third-touch rejection";dir=="SELL"&&bearTrendlineFamily->"trendline third-touch rejection";dir=="BUY"&&bullLevelLadder->"level-ladder continuation";dir=="SELL"&&bearLevelLadder->"level-ladder continuation";dir=="BUY"&&bullLiquidity->"clustered liquidity / SL-hunt reversal";dir=="SELL"&&bearLiquidity->"clustered liquidity / SL-hunt reversal";dir=="BUY"&&bullRetest->"breakout + support-flip retest";dir=="SELL"&&bearRetest->"breakdown + resistance-flip retest";dir=="BUY"&&bullChoch->"CHoCH reversal";dir=="SELL"&&bearChoch->"CHoCH reversal";dir=="BUY"&&bullLevelReaction->"multi-touch level reaction";dir=="SELL"&&bearLevelReaction->"multi-touch level reaction";dir=="BUY"&&bullBreakout->"breakout momentum continuation";dir=="SELL"&&bearBreakout->"breakout momentum continuation";else->"established trend pullback"}\n'''
if anchor5 not in s: raise SystemExit('v33 anchor5 not found')
s=s.replace(anchor5,insert5,1)

anchor6='''    private fun impulseRetracement(c:List<Candle>,direction:String,a:Double):IR?{'''
helpers='''    private fun impulsePauseLevel(c:List<Candle>,direction:String,a:Double):Double?{\n        val w=c.takeLast(min(60,c.size)).dropLast(1);if(w.size<12)return null\n        for(i in (w.size-4) downTo 5){\n            val base=w.subList(i,i+3);val span=base.maxOf{it.h}-base.minOf{it.l};val avgBody=base.map{abs(it.c-it.o)}.average()\n            if(span>a*1.05||avgBody>a*.36)continue\n            val pre=w.subList(i-5,i);val net=pre.last().c-pre.first().o;val energy=pre.sumOf{abs(it.c-it.o)}\n            if(abs(net)<a*1.0||energy<a*1.8)continue\n            if(direction=="BUY"&&net>0)return base.minOf{min(it.o,it.c)}\n            if(direction=="SELL"&&net<0)return base.maxOf{max(it.o,it.c)}\n        }\n        return null\n    }\n\n    private fun oppositeBodyBreakLevel(c:List<Candle>,direction:String,a:Double):Double?{\n        if(c.size<6)return null;val last=c.last();val w=c.takeLast(min(12,c.size)).dropLast(1)\n        return if(direction=="BUY"){\n            val ref=w.asReversed().firstOrNull{it.c<it.o&&abs(it.c-it.o)>=a*.10}?:return null;val lv=max(ref.o,ref.c)\n            if(last.c>lv+a*.04&&last.c>last.o&&last.l<=lv+a*.45&&abs(last.c-lv)<=a*1.60)lv else null\n        }else{\n            val ref=w.asReversed().firstOrNull{it.c>it.o&&abs(it.c-it.o)>=a*.10}?:return null;val lv=min(ref.o,ref.c)\n            if(last.c<lv-a*.04&&last.c<last.o&&last.h>=lv-a*.45&&abs(last.c-lv)<=a*1.60)lv else null\n        }\n    }\n\n    private fun untouchedLiquidityFrontRun(c:List<Candle>,direction:String,target:Double,a:Double):Boolean{\n        val w=c.takeLast(min(14,c.size)).dropLast(1);if(w.size<5)return false\n        for(i in w.lastIndex-1 downTo 1){\n            val x=w[i]\n            if(direction=="BUY"){\n                val gap=target-x.h;if(gap<a*.06||gap>a*.42)continue\n                val later=w.subList(i+1,w.size);if(later.none{it.l<=x.h-a*.35})continue;if(later.any{it.h>=target})continue;return true\n            }else{\n                val gap=x.l-target;if(gap<a*.06||gap>a*.42)continue\n                val later=w.subList(i+1,w.size);if(later.none{it.h>=x.l+a*.35})continue;if(later.any{it.l<=target})continue;return true\n            }\n        }\n        return false\n    }\n\n'''
if anchor6 not in s: raise SystemExit('v33 helper anchor not found')
s=s.replace(anchor6,helpers+anchor6,1)
engine.write_text(s)

# Remove any build wording that exposes implementation-source labels in the public header.
main=Path('app/src/main/java/com/mh/analysis/MainActivityV29.kt')
ms=main.read_text().replace('FOUR-VIDEO CONFLUENCE ENGINE','MARKET STRUCTURE CONFLUENCE')
main.write_text(ms)

# Build metadata.
g=Path('app/build.gradle.kts');gs=g.read_text();gs=gs.replace('versionCode = 32','versionCode = 33').replace('versionName = "32.0"','versionName = "33.0"');g.write_text(gs)
print('v33 structure confirmation patch applied')
